export interface Review {
  id: string;
  userName: string;
  rating: number; // 1-5
  comment: string;
  date: string;
}

export interface Product {
  id: string;
  name: string;
  category: string;
  price: number;
  image: string;
  shortDescription: string;
  ingredients: string[]; // Key elements/materials
  aiDescription?: string; // Generated by Gemini
  rating: number;
  reviews: Review[];
}

export interface CartItem extends Product {
  quantity: number;
}

export interface JournalPost {
  id: string;
  title: string;
  excerpt: string;
  date: string;
  category: string;
  image: string;
  readTime: string;
}

export type Category = 'All' | 'Skincare' | 'Fragrance' | 'Accessories' | 'Sets';
export type ViewState = 'shop' | 'wishlist' | 'about' | 'journal' | 'checkout';